service: crypto-market-app-blz-backend

provider:
  name: aws
  runtime: nodejs12.x
  versionFunctions: false
  stage: dev
  region: eu-west-1
  environment:
    mnemonic: ${env:mnemonic}
    uuid: ${env:uuid}
    chain_id: ${env:chain_id}
    endpoint: ${env:endpoint}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - lambda:*
      Resource:
        - arn:aws:lambda:eu-west-1:*:function:cma-list-update

plugins:
  - serverless-dotenv-plugin

functions:
  updateList:
    handler: updater.list
    name: cma-list-update
    timeout: 600
    events:
      - schedule: rate(10 minutes)

  transferFunds:
    handler: funds.transfer
    name: cma-funds-transfer

  checkAccounts:
    handler: funds.check
    name: cma-funds-check
