service: crypto-market-app-blz-backend

provider:
  name: aws
  runtime: nodejs12.x
  versionFunctions: false
  stage: dev
  region: eu-west-1

functions:
  updateList:
    handler: updater.list
    name: cma-list-update
    timeout: 900
    events:
      - schedule: cron(*/30 * * * ? *)
