service: crypto-market-app-blz-backend

provider:
  name: aws
  runtime: nodejs12.x
  versionFunctions: false
  stage: dev
  region: eu-west-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - lambda:*
      Resource:
        - arn:aws:lambda:eu-west-1:*:function:cma-list-update

functions:
  updateList:
    handler: updater.list
    name: cma-list-update
    timeout: 600
    events:
      - schedule: cron(*/15 * * * ? *)
